name: registro_elettronico
description: Better and faster of the original.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.2+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^2.1.0
  collection: ^1.14.13
  cupertino_icons: null
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  esys_flutter_share: ^1.0.2
  expandable: ^4.1.4
  extended_tabs: ^1.0.1
  f_logs: ^1.2.2
  firebase_analytics: ^6.3.0
  firebase_core: ^0.5.3
  firebase_crashlytics: ^0.2.4
  firebase_messaging: ^7.0.3
  fl_chart: ^0.12.2
  flutter_bloc: ^6.1.1
  flutter_circular_chart: ^0.1.0
  flutter_colorpicker: ^0.3.4
  flutter_email_sender: ^4.0.0
  flutter_launcher_icons: ^0.8.1
  flutter_local_notifications: ^3.0.2
  flutter_secure_storage: ^3.3.5
  flutter_svg: null
  flutter_webview_plugin: ^0.3.11
  get_it: ^5.0.3
  injector: ^1.0.9
  intl: ^0.16.1
  liquid_progress_indicator: ^0.3.2
  liquid_swipe: ^1.5.0
  moor: null
  moor_db_viewer: ^2.0.3
  numberpicker: ^1.3.0
  open_file: ^3.0.3
  package_info: ^0.4.3+2
  path_provider: ^1.6.24
  percent_indicator: ^2.1.9
  pull_to_refresh: ^1.6.3
  random_string: ^2.1.0
  retrofit: ^1.3.4+1
  rxdart: ^0.25.0
  screenshot: ^0.2.0
  shared_preferences: ^0.5.12+4
  sqlite3_flutter_libs: null
  table_calendar: ^2.3.3
  tinycolor: ^1.0.3
  tuple: ^1.0.3
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  json_serializable: ^3.5.1
  moor_generator: null
  retrofit_generator: null

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"

flutter:
  assets:
    - assets/icons/
    - assets/icons/subjects/
    - lang/en.json
    - lang/it.json
  uses-material-design: true
  fonts:
   - family: Manrope
     fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 900
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 200
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 300
    # - family: Montserrat
    #   fonts:
    #     - asset: assets/fonts/Montserrat-Regular.otf
    #     - asset: assets/fonts/Montserrat-Bold.otf
    #       weight: 700
    #     - asset: assets/fonts/Montserrat-Black.otf
    #       weight: 800
    #     - asset: assets/fonts/Montserrat-ExtraBold.otf
    #       weight: 900
    #     - asset: assets/fonts/Montserrat-Italic.otf
    #       style: italic
    #     - asset: assets/fonts/Montserrat-Light.otf
    #       weight: 200
    #     - asset: assets/fonts/Montserrat-Regular.otf
    #       weight: 400
    #     - asset: assets/fonts/Montserrat-Medium.otf
    #       weight: 300
